# Generated by Django 3.2.18 on 2023-07-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumberapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='customuser',
        ),
    ]
