# Generated by Django 3.2.18 on 2023-06-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
