# Generated by Django 3.2.18 on 2023-06-21 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phonenumberapp', '0002_phonenumber_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='customuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phonenumber', to=settings.AUTH_USER_MODEL),
        ),
    ]
