# Generated by Django 3.2.18 on 2023-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumberapp', '0003_alter_phonenumber_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
