# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_bank',
            name='depositor',
            field=models.CharField(max_length=6),
        ),
    ]
