# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna_commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna_comment',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
