# Generated by Django 3.2.18 on 2023-06-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepttype', models.CharField(max_length=15)),
                ('studentid', models.IntegerField()),
                ('content', models.TextField(default='', max_length=500)),
                ('schoolverificationimage', models.ImageField(blank=True, null=True, upload_to='profile_scholarship/')),
                ('school', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_scholarship', to='profileapp.profile')),
            ],
        ),
    ]
