# Generated by Django 3.2.18 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scholarshipapp', '0003_alter_profile_scholarship_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_scholarship',
            name='studentid',
            field=models.IntegerField(choices=[(12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)]),
        ),
    ]
