# Generated by Django 3.2.18 on 2023-06-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_tuition'),
        ('profile_scholarshipapp', '0004_alter_profile_scholarship_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_scholarship',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_scholarship', to='profileapp.profile'),
        ),
    ]
