# Generated by Django 3.2.18 on 2023-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scholarshipapp', '0006_alter_profile_scholarship_schoolverificationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_scholarship',
            name='schoolverificationimage',
            field=models.ImageField(upload_to='profile_scholarship/'),
        ),
    ]
