# Generated by Django 3.2.18 on 2023-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_scholarshipapp', '0011_alter_profile_scholarship_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_scholarship',
            options={'verbose_name_plural': '학력 목록'},
        ),
        migrations.AlterField(
            model_name='profile_scholarship',
            name='accepttype',
            field=models.CharField(choices=[('학생부교과', '학생부교과'), ('학생부종합', '학생부종합'), ('논술', '논술'), ('특기자', '특기자'), ('정시', '정시'), ('기타', '기타')], max_length=20),
        ),
    ]
