# Generated by Django 3.2.18 on 2023-12-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_gpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpaverificationimage', models.ImageField(blank=True, null=True, upload_to='profile_gpa/')),
                ('highschool', models.CharField(max_length=10)),
                ('schooltype', models.CharField(choices=[('영재고', '영재고'), ('과학고', '과학고'), ('국제고', '국제고'), ('외고', '외고'), ('자사고', '자사고'), ('자공고', '자공고'), ('일반고', '일반고'), ('기타', '기타')], max_length=20)),
                ('score', models.TextField(max_length=300)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_gpa', to='profileapp.profile')),
            ],
        ),
    ]
