# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_gpaapp', '0002_auto_20230702_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_gpa',
            name='score',
            field=models.TextField(max_length=300),
        ),
    ]
