# Generated by Django 3.2.18 on 2023-12-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)])),
                ('duration', models.CharField(choices=[('약 1개월', '약 1개월'), ('약 3개월', '약 3개월'), ('약 6개월', '약 6개월'), ('약 9개월', '약 9개월'), ('1년 이상', '1년 이상'), ('진행중', '진행중')], max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('국어', '국어'), ('영어', '영어'), ('수학', '수학'), ('물리', '물리'), ('지구과학', '지구과학'), ('화학', '화학'), ('생명과학', '생명과학'), ('통합과학', '통합과학'), ('생활과윤리', '생활과윤리'), ('윤리와사상', '윤리와사상'), ('한국지리', '한국지리'), ('세계지리', '세계지리'), ('동아시아사', '동아시아사'), ('세계사', '세계사'), ('경제', '경제'), ('정치와법', '정치와법'), ('사회문화', '사회문화'), ('통합사회', '통합사회'), ('한국사', '한국사'), ('예체능', '예체능'), ('기타', '기타')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_career', to='profileapp.profile')),
            ],
        ),
    ]
