# Generated by Django 3.2.18 on 2023-06-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('duration', models.CharField(choices=[('약 3개월', '약 3개월'), ('약 6개월', '약 6개월'), ('약 9개월', '약 9개월'), ('1년 이상', '1년 이상'), ('진행중', '진행중')], max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('국어', '국어'), ('영어', '영어'), ('수학', '수학'), ('물리', '물리'), ('지구과학', '지구과학'), ('생명과학', '생명과학'), ('화학', '화학'), ('학생부', '학생부'), ('기타', '기타')], max_length=20)),
                ('institution', models.CharField(max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_career', to='profileapp.profile')),
            ],
        ),
    ]
