# Generated by Django 3.2.18 on 2023-07-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_career',
            name='institution',
        ),
    ]
