# Generated by Django 3.2.18 on 2023-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0003_auto_20230704_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_career',
            name='month',
            field=models.CharField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile_career',
            name='year',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], max_length=20),
        ),
    ]
