# Generated by Django 3.2.18 on 2023-07-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0004_auto_20230704_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_career',
            name='month',
        ),
    ]
