# Generated by Django 3.2.18 on 2023-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0006_alter_profile_career_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_career',
            name='subject',
            field=models.CharField(choices=[('국어', '국어'), ('영어', '영어'), ('수학', '수학'), ('물리', '물리'), ('지구과학', '지구과학'), ('화학', '화학'), ('생명과학', '생명과학'), ('생활과 윤리', '생활과 윤리'), ('윤리와 사상', '윤리와 사상'), ('한국 지리', '한국 지리'), ('세계 지리', '세계 지리'), ('동아시아사', '동아시아사'), ('세계사', '세계사'), ('경제', '경제'), ('정치와 법', '정치와 법'), ('사회 문화', '사회 문화'), ('한국사', '한국사'), ('기타', '기타')], max_length=20),
        ),
    ]
