# Generated by Django 3.2.18 on 2023-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0008_alter_profile_career_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_career',
            name='duration',
            field=models.CharField(choices=[('약 1개월', '약 1개월'), ('약 3개월', '약 3개월'), ('약 6개월', '약 6개월'), ('약 9개월', '약 9개월'), ('1년 이상', '1년 이상'), ('진행중', '진행중')], max_length=20),
        ),
    ]
