# Generated by Django 3.2.18 on 2023-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_careerapp', '0009_alter_profile_career_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_career',
            name='subject',
            field=models.CharField(choices=[('국어', '국어'), ('영어', '영어'), ('수학', '수학'), ('물리', '물리'), ('지구과학', '지구과학'), ('화학', '화학'), ('생명과학', '생명과학'), ('통합과학', '통합과학'), ('생활과윤리', '생활과윤리'), ('윤리와사상', '윤리와사상'), ('한국지리', '한국지리'), ('세계지리', '세계지리'), ('동아시아사', '동아시아사'), ('세계사', '세계사'), ('경제', '경제'), ('정치와법', '정치와법'), ('사회문화', '사회문화'), ('한국사', '한국사'), ('기타', '기타')], max_length=20),
        ),
    ]
