# Generated by Django 3.2.18 on 2023-07-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_customuser_userrealname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='int_username',
        ),
    ]
