# Generated by Django 3.2.18 on 2023-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='int_username',
            field=models.IntegerField(null=True),
        ),
    ]
