# Generated by Django 3.2.18 on 2023-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_remove_customuser_int_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agree_terms',
            field=models.BooleanField(default=True),
        ),
    ]
