# Generated by Django 3.2.18 on 2023-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_customuser_int_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
