# Generated by Django 3.2.18 on 2023-08-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_alter_customuser_agree_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agree_terms',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
