# Generated by Django 3.2.18 on 2023-12-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_remove_customuser_has_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
