# Generated by Django 3.2.18 on 2023-12-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0014_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
