# Generated by Django 3.2.18 on 2023-07-17 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salaryapp', '0001_initial'),
        ('consultapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', '미결제'), ('paid', '결제완료'), ('cancelled', '결제취소'), ('failed', '결제실패')], db_index=True, default='ready', max_length=9)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('classname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid_ok', models.BooleanField(default=False)),
                ('is_initial_payment', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('consult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='consultapp.consult')),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='salaryapp.salary')),
            ],
        ),
    ]
