# Generated by Django 3.2.18 on 2024-10-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salaryapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid_ok', models.BooleanField(default=False)),
                ('is_initial_payment', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('consult', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='consultapp.consult')),
                ('salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='salaryapp.salary')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
