# Generated by Django 3.2.18 on 2023-07-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_initial_payment',
        ),
    ]
