# Generated by Django 3.2.18 on 2023-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_remove_payment_is_initial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_initial_payment',
            field=models.BooleanField(default=False),
        ),
    ]
