# Generated by Django 3.2.18 on 2023-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_payment_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
