# Generated by Django 3.2.18 on 2023-08-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentapp', '0004_alter_payment_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
