# Generated by Django 3.2.18 on 2023-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0006_auto_20230810_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
