# Generated by Django 3.2.18 on 2023-10-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0007_payment_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_discounted',
        ),
    ]
