# Generated by Django 3.2.18 on 2023-07-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='given_at',
            field=models.DateTimeField(null=True),
        ),
    ]
