# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0002_salary_given_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='depositor',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
