# Generated by Django 3.2.18 on 2023-07-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0005_auto_20230720_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={},
        ),
    ]
