# Generated by Django 3.2.18 on 2023-10-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.CharField(choices=[('graden', 'N수'), ('grade3', '3학년'), ('grade2', '2학년'), ('grade1', '1학년'), ('middle', '중등')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='userrealname',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
