# Generated by Django 3.2.18 on 2023-07-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_planapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_plan',
            name='content',
            field=models.TextField(blank=True, default='학습 플랜 작성', max_length=1000, null=True),
        ),
    ]
