# Generated by Django 3.2.18 on 2023-07-12 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_planapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_plan',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 17, 47, 36, 473218)),
        ),
    ]
