# Generated by Django 3.2.18 on 2023-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_planapp', '0002_feedback_plan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
