# Generated by Django 3.2.18 on 2023-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_planapp', '0002_alter_feedback_plan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_plan',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
