# Generated by Django 3.2.18 on 2023-07-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult_feedback',
            name='assignment',
            field=models.TextField(default='학생 종합 분석 작성', max_length=1000),
        ),
    ]
