# Generated by Django 3.2.18 on 2023-08-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_feedbackapp', '0002_alter_consult_feedback_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult_feedback',
            name='todo',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
