# Generated by Django 3.2.18 on 2023-07-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_feedbackapp', '0002_consult_feedback_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult_feedback',
            name='assignment',
        ),
    ]
