# Generated by Django 3.2.18 on 2023-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_coachapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_coach',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
