# Generated by Django 3.2.18 on 2023-07-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_introductionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_introduction',
            name='content',
            field=models.TextField(max_length=80),
        ),
    ]
