# Generated by Django 3.2.18 on 2023-07-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='belong',
            field=models.CharField(max_length=8),
        ),
    ]
