# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0002_alter_consult_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='problem',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='consult',
            name='strategy',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='consult',
            name='want',
            field=models.TextField(default='', max_length=500),
        ),
    ]
