# Generated by Django 3.2.18 on 2023-07-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0004_alter_consult_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='problem',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consult',
            name='strategy',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consult',
            name='want',
            field=models.TextField(max_length=500),
        ),
    ]
