# Generated by Django 3.2.18 on 2023-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0005_auto_20230727_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
