# Generated by Django 3.2.18 on 2023-08-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0006_consult_is_waiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='is_waiting',
        ),
    ]
