# Generated by Django 3.2.18 on 2023-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultapp', '0007_remove_consult_is_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='is_warned',
            field=models.BooleanField(default=False),
        ),
    ]
