# Generated by Django 3.2.18 on 2023-12-27 23:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_consulttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulttype', multiselectfield.db.fields.MultiSelectField(choices=[('정시', '정시'), ('내신', '내신'), ('학생부', '학생부'), ('중등', '중등')], max_length=20)),
                ('content', models.TextField(max_length=300, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_consulttype', to='profileapp.profile')),
            ],
        ),
    ]
