# Generated by Django 3.2.18 on 2023-06-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_consulttypeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_consulttype',
            old_name='target',
            new_name='targetstudent',
        ),
    ]
