# Generated by Django 3.2.18 on 2023-07-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_consulttypeapp', '0002_rename_target_profile_consulttype_targetstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_consulttype',
            name='targetstudent',
        ),
    ]
