# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_consulttypeapp', '0003_remove_profile_consulttype_targetstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_consulttype',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
