# Generated by Django 3.2.18 on 2023-07-20 19:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile_consulttypeapp', '0004_alter_profile_consulttype_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_consulttype',
            name='consulttype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('정시', '정시'), ('내신', '내신'), ('학생부', '학생부'), ('중등', '중등')], max_length=20),
        ),
    ]
