# Generated by Django 3.2.18 on 2023-06-30 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepttype', models.CharField(choices=[('학생부교과', '학생부교과'), ('학생부종합', '학생부종합'), ('논술', '논술'), ('특기자', '특기자'), ('정시', '정시'), ('기타', '기타')], max_length=20)),
                ('studentid', models.IntegerField(choices=[(12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)])),
                ('schoolimage', models.ImageField(upload_to='teacherapply_schoolverification/')),
                ('userimage', models.ImageField(upload_to='teacherapply_userverification/')),
                ('school', models.CharField(max_length=15)),
                ('major', models.CharField(max_length=15)),
                ('bank', models.CharField(choices=[('BNK부산은행', 'BNK부산은행'), ('DGB대구은행', 'DGB대구은행'), ('IBK기업은행', 'IBK기업은행'), ('KB국민은행', 'KB국민은행'), ('MG새마을금고', 'MG새마을금고'), ('SC제일은행', 'SC제일은행'), ('Sh수협은행', 'Sh수협은행'), ('광주은행', '광주은행'), ('농협', '농협'), ('신한은행', '신한은행'), ('신협', '신협'), ('우리은행', '우리은행'), ('우체국은행', '우체국은행'), ('저축은행', '저축은행'), ('카카오뱅크', '카카오뱅크'), ('케이뱅크', '케이뱅크'), ('토스', '토스'), ('하나은행', '하나은행')], max_length=20)),
                ('accountnumber', models.CharField(max_length=30)),
                ('depositor', models.CharField(max_length=10)),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacherapply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
