# Generated by Django 3.2.18 on 2024-02-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='studentid',
            field=models.IntegerField(choices=[(9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], null=True),
        ),
    ]
