# Generated by Django 3.2.18 on 2023-06-30 10:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0002_teacherapply_consulttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='consulttype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('정시', '정시'), ('내신', '내신'), ('학생부', '학생부'), ('논술', '논술')], max_length=20),
        ),
    ]
