# Generated by Django 3.2.18 on 2023-07-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0004_alter_teacherapply_consulttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapply',
            name='has_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherapply',
            name='has_userimage',
            field=models.BooleanField(default=False),
        ),
    ]
