# Generated by Django 3.2.18 on 2023-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0005_auto_20230723_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapply',
            name='has_schoolimage',
            field=models.BooleanField(default=False),
        ),
    ]
