# Generated by Django 3.2.18 on 2023-07-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0005_alter_teacherapply_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='studentid',
            field=models.IntegerField(choices=[(12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)]),
        ),
    ]
