# Generated by Django 3.2.18 on 2023-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0006_alter_teacherapply_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='accountnumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
