# Generated by Django 3.2.18 on 2023-07-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0007_alter_teacherapply_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='schoolimage',
            field=models.ImageField(upload_to='teacherapply/'),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='userimage',
            field=models.ImageField(upload_to='teacherapply/'),
        ),
    ]
