# Generated by Django 3.2.18 on 2023-07-15 01:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapplyapp', '0008_auto_20230715_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapply',
            name='accepttype',
            field=models.CharField(choices=[('학생부교과', '학생부교과'), ('학생부종합', '학생부종합'), ('논술', '논술'), ('특기자', '특기자'), ('정시', '정시'), ('기타', '기타')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='bank',
            field=models.CharField(choices=[('BNK부산은행', 'BNK부산은행'), ('DGB대구은행', 'DGB대구은행'), ('IBK기업은행', 'IBK기업은행'), ('KB국민은행', 'KB국민은행'), ('MG새마을금고', 'MG새마을금고'), ('SC제일은행', 'SC제일은행'), ('Sh수협은행', 'Sh수협은행'), ('광주은행', '광주은행'), ('농협', '농협'), ('신한은행', '신한은행'), ('신협', '신협'), ('우리은행', '우리은행'), ('우체국은행', '우체국은행'), ('저축은행', '저축은행'), ('카카오뱅크', '카카오뱅크'), ('케이뱅크', '케이뱅크'), ('토스', '토스'), ('하나은행', '하나은행')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='consulttype',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('정시', '정시'), ('내신', '내신'), ('학생부', '학생부'), ('논술', '논술')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='depositor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='major',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='school',
            field=models.CharField(choices=[('가천대학교', '가천대학교'), ('가톨릭관동대학교', '가톨릭관동대학교'), ('가톨릭대학교', '가톨릭대학교'), ('강원대학교', '강원대학교'), ('건국대학교', '건국대학교'), ('건양대학교', '건양대학교'), ('경북대학교', '경북대학교'), ('경상국립대학교', '경상국립대학교'), ('경희대학교', '경희대학교'), ('계명대학교', '계명대학교'), ('고려대학교', '고려대학교'), ('고신대학교', '고신대학교'), ('단국대학교', '단국대학교'), ('대구가톨릭대학교', '대구가톨릭대학교'), ('동국대학교(경주)', '동국대학교(경주)'), ('동아대학교', '동아대학교'), ('부산대학교', '부산대학교'), ('서울대학교', '서울대학교'), ('성균관대학교', '성균관대학교'), ('순천향대학교', '순천향대학교'), ('아주대학교', '아주대학교'), ('연세대학교(서울)', '연세대학교(서울)'), ('연세대학교(미래)', '연세대학교(미래)'), ('영남대학교', '영남대학교'), ('울산대학교', '울산대학교'), ('원광대학교', '원광대학교'), ('을지대학교', '을지대학교'), ('이화여자대학교', '이화여자대학교'), ('인제대학교', '인제대학교'), ('인하대학교', '인하대학교'), ('전남대학교', '전남대학교'), ('전북대학교', '전북대학교'), ('제주대학교', '제주대학교'), ('조선대학교', '조선대학교'), ('중앙대학교', '중앙대학교'), ('차의과학대학교', '차의과학대학교'), ('충남대학교', '충남대학교'), ('충북대학교', '충북대학교'), ('한림대학교', '한림대학교'), ('한양대학교', '한양대학교')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='studentid',
            field=models.IntegerField(choices=[(12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True),
        ),
        migrations.AlterField(
            model_name='teacherapply',
            name='userimage',
            field=models.ImageField(null=True, upload_to='teacherapply/'),
        ),
    ]
