# Generated by Django 3.2.18 on 2023-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refusalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refusal',
            name='type',
            field=models.CharField(choices=[('matching', '매칭 종료'), ('consult', '수업 종료'), ('teacherapply', '수업 신청 종료'), ('refund', '수업 환불 완료')], default='matching', max_length=20),
        ),
    ]
