# Generated by Django 3.2.18 on 2023-07-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refusalapp', '0002_refusal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusal',
            name='content',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
