# Generated by Django 3.2.18 on 2023-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refusalapp', '0003_alter_refusal_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusal',
            name='content',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
