# Generated by Django 3.2.18 on 2023-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refusalapp', '0005_alter_refusal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusal',
            name='content',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='refusal',
            name='type',
            field=models.CharField(choices=[('matching', '매칭 종료'), ('consult', '컨설팅 종료'), ('teacherapply', '컨설팅 신청 종료'), ('refund', '컨설팅 환불 완료')], default='matching', max_length=30),
        ),
    ]
