# Generated by Django 3.2.18 on 2023-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refusalapp', '0006_auto_20230811_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refusal',
            name='content',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
