# Generated by Django 3.2.18 on 2023-07-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refusalreason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=15)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refusalreason', to='applicationapp.application')),
            ],
        ),
    ]
