# Generated by Django 3.2.18 on 2023-07-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationapp', '0001_initial'),
        ('application_refusalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_refusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=15)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_refusal', to='applicationapp.application')),
            ],
        ),
        migrations.DeleteModel(
            name='Refusalreason',
        ),
    ]
