# Generated by Django 3.2.18 on 2023-06-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('abled', '모집중'), ('disabled', '모집 중지')], default='disabled', max_length=20)),
                ('tuition', models.IntegerField(choices=[(16, 'beginner (15)'), (19, 'intermediate (18)'), (22, 'advanced (21)'), (25, 'expert (25)'), (30, 'master (30)')], default=16)),
                ('payment_updated_at', models.DateField(null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
