# Generated by Django 3.2.18 on 2024-10-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=False)),
                ('tuition', models.IntegerField(choices=[(160000, '160000 (4주 16만원)'), (200000, '200000 (4주 20만원)'), (250000, '250000 (4주 25만원)'), (300000, '300000 (4주 30만원)'), (350000, '350000 (4주 35만원)')], default=160000)),
                ('payment_updated_at', models.DateField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
