# Generated by Django 3.2.18 on 2023-12-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tuition',
            field=models.IntegerField(choices=[(160000, '160000 (4주 16만원)'), (200000, '200000 (4주 20만원)'), (250000, '250000 (4주 25만원)'), (300000, '300000 (4주 30만원)'), (350000, '350000 (4주 35만원)')], default=160000),
        ),
    ]
