# Generated by Django 3.2.18 on 2023-06-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
