# Generated by Django 3.2.18 on 2023-06-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_alter_profile_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tuition',
            field=models.IntegerField(choices=[(16, 'beginner (15만원)'), (19, 'intermediate (18만원)'), (22, 'advanced (21만원)'), (25, 'expert (25만원)'), (30, 'master (30만원)')], default=16),
        ),
    ]
