# Generated by Django 3.2.18 on 2023-12-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
