# Generated by Django 3.2.18 on 2023-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tuition',
            field=models.IntegerField(choices=[(16, '160000 (16만원)'), (18, '180000 (18만원)'), (20, '200000 (20만원)'), (22, '220000 (22만원)'), (24, '240000 (24만원)'), (26, '260000 (26만원)'), (28, '280000 (28만원)'), (30, '300000 (30만원)'), (32, '320000 (32만원)')], default=16),
        ),
    ]
