# Generated by Django 3.2.18 on 2023-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_alter_profile_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tuition',
            field=models.IntegerField(choices=[(16, '160000 (4주/16만원)'), (18, '180000 (4주/18만원)'), (20, '200000 (4주/20만원)'), (22, '220000 (4주/22만원)'), (24, '240000 (4주/24만원)'), (26, '260000 (4주/26만원)'), (28, '280000 (4주/28만원)'), (30, '300000 (4주/30만원)'), (32, '320000 (4주/32만원)')], default=16),
        ),
    ]
