# Generated by Django 3.2.18 on 2023-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tuition',
            field=models.IntegerField(choices=[(1600, '160000 (4주/16만원)'), (1800, '180000 (4주/18만원)'), (2000, '200000 (4주/20만원)'), (2200, '220000 (4주/22만원)'), (2400, '240000 (4주/24만원)'), (2600, '260000 (4주/26만원)'), (2800, '280000 (4주/28만원)'), (3000, '300000 (4주/30만원)'), (3200, '320000 (4주/32만원)')], default=1600),
        ),
    ]
