# Generated by Django 3.2.18 on 2023-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
