# Generated by Django 3.2.18 on 2023-12-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult_qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='consult_qna/')),
                ('content', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_qna', to='consultapp.consult')),
            ],
        ),
    ]
