# Generated by Django 3.2.18 on 2023-12-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homescreenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageview',
            old_name='view',
            new_name='count',
        ),
    ]
