# Generated by Django 3.2.18 on 2023-12-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termofuse', models.TextField(blank=True, max_length=200, null=True)),
                ('privacypolicy', models.TextField(blank=True, max_length=200, null=True)),
                ('announcement', models.TextField(blank=True, max_length=200, null=True)),
                ('blog', models.TextField(blank=True, max_length=200, null=True)),
                ('instagram', models.TextField(blank=True, max_length=200, null=True)),
                ('kakaotalk', models.TextField(blank=True, max_length=200, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
