# Generated by Django 3.2.18 on 2023-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termofuse', models.TextField(max_length=200)),
                ('privacypolicy', models.TextField(max_length=200)),
                ('aboutus', models.TextField(max_length=200)),
                ('phonenumber', models.TextField(max_length=200)),
                ('kakaotalk', models.TextField(max_length=200)),
            ],
        ),
    ]
