# Generated by Django 3.2.18 on 2023-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund', models.FileField(upload_to='document/')),
                ('termofuse', models.FileField(upload_to='document/')),
                ('privacypolicy', models.FileField(upload_to='document/')),
                ('kakaotalk', models.TextField(max_length=100)),
                ('termofuse_updated', models.DateField()),
                ('refund_updated', models.DateField()),
                ('privacypolicy_updated', models.DateField()),
            ],
        ),
    ]
