# Generated by Django 3.2.18 on 2023-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='kakaotalk',
            field=models.TextField(max_length=200),
        ),
    ]
