# Generated by Django 3.2.18 on 2023-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='document',
            name='kakaotalk',
        ),
        migrations.RemoveField(
            model_name='document',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='document',
            name='privacypolicy',
        ),
        migrations.RemoveField(
            model_name='document',
            name='termofuse',
        ),
        migrations.AddField(
            model_name='document',
            name='aboutus_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kakaotalk_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='phonenumber_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='privacypolicy_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='termofuse_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
