# Generated by Django 3.2.18 on 2023-07-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0002_alter_document_kakaotalk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='document',
            name='refund_updated',
        ),
    ]
