# Generated by Django 3.2.18 on 2023-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0002_auto_20230724_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='kakaotalk_link',
            new_name='kakaotalk',
        ),
        migrations.RemoveField(
            model_name='document',
            name='phonenumber_link',
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
