# Generated by Django 3.2.18 on 2023-08-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0003_auto_20230724_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='announcement_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
