# Generated by Django 3.2.18 on 2023-08-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0004_document_announcement_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='aboutus_link',
        ),
    ]
