# Generated by Django 3.2.18 on 2023-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0005_remove_document_aboutus_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
