# Generated by Django 3.2.18 on 2023-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0006_document_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
