# Generated by Django 3.2.18 on 2023-08-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0007_alter_document_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blog_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='instagram',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
