# Generated by Django 3.2.18 on 2023-08-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0008_auto_20230828_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='announcement_link',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='blog_link',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='email',
            new_name='privacypolicy',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='termofuse_link',
            new_name='termofuse',
        ),
        migrations.RemoveField(
            model_name='document',
            name='privacypolicy_link',
        ),
    ]
