# Generated by Django 3.2.18 on 2023-06-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satverificationimage', models.ImageField(blank=True, null=True, upload_to='profile_sat/')),
                ('satyear', models.IntegerField()),
                ('score', models.TextField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sat', to='profileapp.profile')),
            ],
        ),
    ]
