# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_satapp', '0005_alter_profile_sat_satyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_sat',
            name='score',
            field=models.TextField(max_length=300),
        ),
    ]
