# Generated by Django 3.2.18 on 2023-07-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_satapp', '0007_alter_profile_sat_satverificationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_sat',
            name='satverificationimage',
            field=models.ImageField(upload_to='profile_sat/'),
        ),
    ]
