# Generated by Django 3.2.18 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_classlinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult_classlink',
            name='classtime',
            field=models.CharField(max_length=10),
        ),
    ]
