# Generated by Django 3.2.18 on 2023-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_classlinkapp', '0003_alter_consult_classlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult_classlink',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
