# Generated by Django 3.2.18 on 2023-07-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('initial', '신청대기'), ('applied', '신청완료'), ('matching', '매칭중'), ('denied', '거절'), ('waiting', '입금대기'), ('ongoing', '진행중')], default='applied', max_length=20),
        ),
    ]
