# Generated by Django 3.2.18 on 2023-07-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationapp', '0002_alter_application_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.CharField(choices=[('graden', 'N수'), ('grade3', '3학년'), ('grade2', '2학년'), ('grade1', '1학년'), ('middle', '중등')], max_length=20),
        ),
    ]
