# Generated by Django 3.2.18 on 2023-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='depositor',
            field=models.CharField(max_length=20),
        ),
    ]
