# Generated by Django 3.2.18 on 2023-07-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refundapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='student',
        ),
    ]
