# Generated by Django 3.2.18 on 2023-07-15 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refundapp', '0002_remove_refund_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund', to=settings.AUTH_USER_MODEL),
        ),
    ]
