# Generated by Django 3.2.18 on 2023-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refundapp', '0002_alter_refund_depositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='given_at',
            field=models.DateTimeField(null=True),
        ),
    ]
