# Generated by Django 3.2.18 on 2023-10-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refundapp', '0003_refund_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
    ]
