# Generated by Django 3.2.18 on 2023-07-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refundapp', '0003_refund_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='entire_amount',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='is_extended_refund',
        ),
    ]
