# Generated by Django 3.2.18 on 2023-10-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refundapp', '0004_refund_is_discounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='is_discounted',
        ),
    ]
